version: '3.4'

services:
  posterr:
    image: posterr
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      TZ: "Australia/Brisbane"
      BASEURL: ""
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]


